### ISSUE TITLE
Exeption when call without args

### ISSUE THREAD

**Issue by iaroslavscript** [devopshq/crosspm#15]
```console
~$ python -m"crosspm.cpm"
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/main/devpython/3.4_crosspm/lib/python3.4/site-packages/crosspm/cpm.py", line 222, in <module>
    main()
  File "/media/main/devpython/3.4_crosspm/lib/python3.4/site-packages/crosspm/cpm.py", line 217, in main
    args.check_args( args )
AttributeError: 'Namespace' object has no attribute 'check_args'
```

However:
```console
~$ python -m"crosspm.cpm" --help
usage: PROG [-h] {download,promote,pack} ...

positional arguments:
  {download,promote,pack}
                        sub-command help
    download            a download help
    promote             a promote help
    pack                a pack help

optional arguments:
  -h, --help            show this help message and exit
```

**Comment by iaroslavscript** [comment]
Merged to develop https://github.com/devopshq/crosspm/pull/20
